policies:
  - name: Update Go version
    config:
      - "updatecli.d/go.yaml"
    values:
      - values.yaml
  - name: Update Helm chart dependencies and Hauler manifest
    config:
      - ./updatecli.d/update-chart-deps.yaml
      - ./updatecli.d/update-hauler-manifest.yaml
    values:
      - ./update-deps-values.yaml
