name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  linter:
    name: "Run Golang linter"
    uses: jvanz/kubewarden-controller/.github/workflows/golangci-lint.yml@main
  unit-tests:
    name: "Run unit tests"
    uses: jvanz/kubewarden-controller/.github/workflows/unit-test.yml@main
  build-container-image:
    name: "Build container image"
    uses: jvanz/kubewarden-controller/.github/workflows/container-image.yml@main
    needs: unit-tests
    if: ${{github.event_name == 'push' && github.ref_name == 'main'}}
